export default [
  {id: 'ROLE_SUPER_ADMIN', name: 'resources.groups.custom.roles.role_super_admin'},
  {id: 'ROLE_ADMIN', name: 'resources.groups.custom.roles.role_admin'},
  {id: 'ROLE_DOCTOR', name: 'resources.groups.custom.roles.role_doctor'},
  {id: 'ROLE_PATIENT', name: 'resources.groups.custom.roles.role_patient'},
  {id: 'ROLE_USER', name: 'resources.groups.custom.roles.role_user'},

  {id: 'USERS_LIST', name: 'resources.groups.custom.roles.users_list'},
  {id: 'USERS_SHOW', name: 'resources.groups.custom.roles.users_show'},
  {id: 'USERS_EDIT', name: 'resources.groups.custom.roles.users_edit'},
  {id: 'USERS_EDIT_GROUPS', name: 'resources.groups.custom.roles.users_edit_groups'},
  {id: 'USERS_EDIT_PATIENTS', name: 'resources.groups.custom.roles.users_edit_patients'},
  {id: 'USERS_EDIT_DOCTORS', name: 'resources.groups.custom.roles.users_edit_doctors'},
  {id: 'USERS_CREATE', name: 'resources.groups.custom.roles.users_create'},

  {id: 'GROUPS_LIST', name: 'resources.groups.custom.roles.groups_list'},
  {id: 'GROUPS_SHOW', name: 'resources.groups.custom.roles.groups_show'},
  {id: 'GROUPS_EDIT', name: 'resources.groups.custom.roles.groups_edit'},
  {id: 'GROUPS_CREATE', name: 'resources.groups.custom.roles.groups_create'},

  {id: 'DIAGNOSTICS_EDIT', name: 'resources.groups.custom.roles.diagnostics_edit'},
  {id: 'DIAGNOSTICS_CREATE', name: 'resources.groups.custom.roles.diagnostics_create'},
  {id: 'DIAGNOSTICS_LIST_USERS', name: 'resources.groups.custom.roles.diagnostics_list_users'},
  {id: 'DIAGNOSTICS_LIST_CREATED', name: 'resources.groups.custom.roles.diagnostics_list_created'},
  {id: 'DIAGNOSTICS_LIST_UPDATED', name: 'resources.groups.custom.roles.diagnostics_list_updated'},
  {id: 'DIAGNOSTICS_SHOW_USER', name: 'resources.groups.custom.roles.diagnostics_show_user'},

  {id: 'RECOMMENDATIONS_LIST', name: 'resources.groups.custom.roles.recommendations_list'},
  {id: 'RECOMMENDATIONS_EDIT', name: 'resources.groups.custom.roles.recommendations_edit'},
  {id: 'RECOMMENDATIONS_SHOW', name: 'resources.groups.custom.roles.recommendations_show'},
  {id: 'RECOMMENDATIONS_CREATE', name: 'resources.groups.custom.roles.recommendations_create'},
  {id: 'RECOMMENDATIONS_LIST_USERS', name: 'resources.groups.custom.roles.recommendations_list_users'},
  {id: 'RECOMMENDATIONS_LIST_CREATED', name: 'resources.groups.custom.roles.recommendations_list_created'},
  {id: 'RECOMMENDATIONS_LIST_UPDATED', name: 'resources.groups.custom.roles.recommendations_list_updated'},
  {id: 'RECOMMENDATIONS_LIST_AS_CALENDAR', name: 'resources.groups.custom.roles.recommendations_list_as_calendar'},
  {id: 'RECOMMENDATIONS_SHOW_USERS', name: 'resources.groups.custom.roles.recommendations_show_users'},

  {id: 'VISITS_EDIT', name: 'resources.groups.custom.roles.visits_edit'},
  {id: 'VISITS_CREATE', name: 'resources.groups.custom.roles.visits_create'},
  {id: 'VISITS_LIST_USERS', name: 'resources.groups.custom.roles.visits_list_users'},
  {id: 'VISITS_LIST_CREATED', name: 'resources.groups.custom.roles.visits_list_created'},
  {id: 'VISITS_LIST_UPDATED', name: 'resources.groups.custom.roles.visits_list_updated'},
  {id: 'VISITS_LIST_AS_CALENDAR', name: 'resources.groups.custom.roles.visits_list_as_calendar'},

  {id: 'TRAININGS_EDIT', name: 'resources.groups.custom.roles.trainings_edit'},
  {id: 'TRAININGS_SHOW', name: 'resources.groups.custom.roles.trainings_show'},
  {id: 'TRAININGS_CREATE', name: 'resources.groups.custom.roles.trainings_create'},
  {id: 'TRAININGS_LIST_USERS', name: 'resources.groups.custom.roles.trainings_list_users'},
  {id: 'TRAININGS_LIST_CREATED', name: 'resources.groups.custom.roles.trainings_list_created'},
  {id: 'TRAININGS_LIST_UPDATED', name: 'resources.groups.custom.roles.trainings_list_updated'},
  {id: 'TRAININGS_LIST_AS_CALENDAR', name: 'resources.groups.custom.roles.trainings_list_as_calendar'},
  {id: 'TRAININGS_SHOW_USER', name: 'resources.groups.custom.roles.trainings_show_user'},

  {id: 'CONSULTATIONS_EDIT', name: 'resources.groups.custom.roles.consultations_edit'},
  {id: 'CONSULTATIONS_SHOW', name: 'resources.groups.custom.roles.consultations_show'},
  {id: 'CONSULTATIONS_CREATE', name: 'resources.groups.custom.roles.consultations_create'},
  {id: 'CONSULTATIONS_LIST_USERS', name: 'resources.groups.custom.roles.consultations_list_users'},
  {id: 'CONSULTATIONS_LIST_CREATED', name: 'resources.groups.custom.roles.consultations_list_created'},
  {id: 'CONSULTATIONS_LIST_UPDATED', name: 'resources.groups.custom.roles.consultations_list_updated'},
  {id: 'CONSULTATIONS_SHOW_USER', name: 'resources.groups.custom.roles.consultations_show_user'},

  {id: 'PSYCHO_PHYSICAL_DEVELOPMENT_EDIT', name: 'resources.groups.custom.roles.psycho_physical_development_edit'},
  {id: 'PSYCHO_PHYSICAL_DEVELOPMENT_SHOW', name: 'resources.groups.custom.roles.psycho_physical_development_show'},
  {id: 'PSYCHO_PHYSICAL_DEVELOPMENT_SHOW_USER', name: 'resources.groups.custom.roles.psycho_physical_development_show_user'},
  {id: 'PSYCHO_PHYSICAL_DEVELOPMENT_CREATE', name: 'resources.groups.custom.roles.psycho_physical_development_create'},
  {id: 'PSYCHO_PHYSICAL_DEVELOPMENT_LIST_USER', name: 'resources.groups.custom.roles.psycho_physical_development_list_user'},
  {id: 'PSYCHO_PHYSICAL_DEVELOPMENT_LIST_CREATED', name: 'resources.groups.custom.roles.psycho_physical_development_list_created'},
  {id: 'PSYCHO_PHYSICAL_DEVELOPMENT_LIST_UPDATED', name: 'resources.groups.custom.roles.psycho_physical_development_list_updated'},

  {id: 'MEASUREMENT_TYPES_LIST', name: 'resources.groups.custom.roles.measurement_types_list'},
  {id: 'MEASUREMENT_TYPES_EDIT', name: 'resources.groups.custom.roles.measurement_types_edit'},
  {id: 'MEASUREMENT_TYPES_CREATE', name: 'resources.groups.custom.roles.measurement_types_create'},
  {id: 'MEASUREMENTS_LIST_USERS', name: 'resources.groups.custom.roles.measurements_list_users'},
  {id: 'MEASUREMENTS_LIST_UPDATED', name: 'resources.groups.custom.roles.measurements_list_updated'},
  {id: 'MEASUREMENTS_CREATE_USERS', name: 'resources.groups.custom.roles.measurements_  create_users'},
  {id: 'MEASUREMENTS_EDIT_USERS', name: 'resources.groups.custom.roles.measurements_edit_users'},

  {id: 'MEDIA_OBJECTS_LIST', name: 'resources.groups.custom.roles.media_objects_list'},

  {id: 'INFORMATION_FROM_PATIENT_CREATE', name: 'resources.groups.custom.roles.information_from_patient_create'},
  {id: 'INFORMATION_FROM_PATIENT_LIST_USERS', name: 'resources.groups.custom.roles.information_from_patient_list_users'},
  {id: 'INFORMATION_FROM_PATIENT_LIST_CREATED', name: 'resources.groups.custom.roles.information_from_patient_list_created'},

  {id: 'IMAGING_EXAMINATIONS_CREATE', name: 'resources.groups.custom.roles.imaging_examinations_create'},
  {id: 'IMAGING_EXAMINATIONS_LIST_USERS', name: 'resources.groups.custom.roles.imaging_examinations_list_users'},
  {id: 'IMAGING_EXAMINATIONS_LIST_CREATED', name: 'resources.groups.custom.roles.imaging_examinations_list_created'},

  {id: 'MEDICAL_EXAMINATIONS_CREATE', name: 'resources.groups.custom.roles.medical_examinations_create'},
  {id: 'MEDICAL_EXAMINATIONS_EDIT', name: 'resources.groups.custom.roles.medical_examinations_edit'},
  {id: 'MEDICAL_EXAMINATIONS_LIST_USERS', name: 'resources.groups.custom.roles.medical_examinations_list_users'},
  {id: 'MEDICAL_EXAMINATIONS_LIST_CREATED', name: 'resources.groups.custom.roles.medical_examinations_list_created'},
  {id: 'MEDICAL_EXAMINATIONS_LIST_UPDATED', name: 'resources.groups.custom.roles.medical_examinations_list_updated'},
  {id: 'MEDICAL_EXAMINATIONS_LIST_AS_CALENDAR', name: 'resources.groups.custom.roles.medical_examinations_list_as_calendar'},

  {id: 'MEDICAL_RECOMMENDATIONS_CREATE', name: 'resources.groups.custom.roles.medical_recommendations_create'},
  {id: 'MEDICAL_RECOMMENDATIONS_EDIT', name: 'resources.groups.custom.roles.medical_recommendations_edit'},
  {id: 'MEDICAL_RECOMMENDATIONS_EDIT_CREATED', name: 'resources.groups.custom.roles.medical_recommendations_edit_created'},
  {id: 'MEDICAL_RECOMMENDATIONS_LIST_USER', name: 'resources.groups.custom.roles.medical_recommendations_list_user'},
  {id: 'MEDICAL_RECOMMENDATIONS_LIST_CREATED', name: 'resources.groups.custom.roles.medical_recommendations_list_created'},
  {id: 'MEDICAL_RECOMMENDATIONS_LIST_UPDATED', name: 'resources.groups.custom.roles.medical_recommendations_list_updated'},

  {id: 'DIET_RECOMMENDATIONS_CREATE', name: 'resources.groups.custom.roles.diet_recommendations_create'},
  {id: 'DIET_RECOMMENDATIONS_EDIT', name: 'resources.groups.custom.roles.diet_recommendations_edit'},
  {id: 'DIET_RECOMMENDATIONS_EDIT_CREATED', name: 'resources.groups.custom.roles.diet_recommendations_edit_created'},
  {id: 'DIET_RECOMMENDATIONS_LIST_USER', name: 'resources.groups.custom.roles.diet_recommendations_list_user'},
  {id: 'DIET_RECOMMENDATIONS_LIST_CREATED', name: 'resources.groups.custom.roles.diet_recommendations_list_created'},
  {id: 'DIET_RECOMMENDATIONS_LIST_UPDATED', name: 'resources.groups.custom.roles.diet_recommendations_list_updated'},
];
